### ISSUE TITLE
Correct BP quiz pointers for watsonx.ai and watsonx.data

### ISSUE THREAD

**Issue by ridgill** [ibm-build-lab/VAD-VAR-Workshop#246]
Current quiz pointers are to ONLY the quiz page, which will not result in the badge being attained. Update both watsonx.ai and watsonx.data pointers from the existing links that point only to the quiz to the below links that point to the overall course.

**AC**
- Add a section at the end of lab 103 for AI to indicate that the quiz can now be completed.  Provide a pointer to the BP course.  Mention that the labs have covered all course content except for the quiz so users do not ned to watch the videos, they can just click through the sections and take the quiz. 
- Add a section at the end of the watsonx.data lab (or maybe at whatever point all the quiz questions can be answered - I think this is at end of 106), add a similar notification and pointer to the course. 
- Update all other course pointers that exist (on the root ai and root data pages) so they point at the links below. 

**L3 watsonx.ai BP course:** https://learn.ibm.com/course/view.php?id=13452
**L3 watsonx.data BP course:** https://learn.ibm.com/course/view.php?id=13171

**Comment by MaxShapiro32** [comment]
Fixed and merged [here](https://github.com/ibm-build-lab/VAD-VAR-Workshop/pull/249)
