### ISSUE TITLE
watsonx.ai Prompt Engineer

### ISSUE THREAD

**Issue by r2raman** [ibm-build-lab/VAD-VAR-Workshop#266]
Review Prompt Engineering practitioner document and determine if the content within the document can be pulled out into its own lab or can supplement an existing watsonx.ai lab. 

Practitioner Document Reference: https://ibm.ent.box.com/s/au9pi10bcqtrij0tun3xknlcj5fmlxf9 

AC: Review the practitioner documents and create new tasks for updating x.ai lab / creating a new lab focused on prompt engineering OR determine that existing material is sufficient and no new material is needed from the prompt engineer practitioner documents.

**Comment by jbukuts** [comment]
Most of the content here seems to coincide with much of our existing L3 content. For that reason, moving this task to completed.
