### ISSUE TITLE
IBM watsonx.governance for Technical Sales Level 3

### ISSUE THREAD

**Issue by r2raman** [ibm-build-lab/VAD-VAR-Workshop#278]
https://yourlearning.ibm.com/activity/PLAN-07AEB3D2563D

**Comment by MaxShapiro32** [comment]
The plan is to divide the L3 labs up into the following labs:

- **1:** Environment Setup
- **102:** Define an AI model use case
- **103:** Setup watsonx.ai project
- **104:** Track the AI model
- **105:** Deploy the AI model
- **106:** Evaluate the AI model

**Comment by MaxShapiro32** [comment]
Labs are done and a PR is created here: https://github.com/ibm-build-lab/VAD-VAR-Workshop/pull/337
