### ISSUE TITLE
watsonx Assistant L4 Lab 7: LLM-Powered Search

### ISSUE THREAD

**Issue by tkmonson** [ibm-build-lab/VAD-VAR-Workshop#301]
This task is part of #264.

Create a lab based on [Part 7](https://ibm.seismic.com/app#/doccenter/861ea1fd-99e0-44d7-9135-85412e5c28d1/doc/%252Fdd3359e5f7-a856-a91b-7688-41024b2ac637%252FdfNTY4NmVhOWItY2RkNS04ZWY3LTZkNzItZTQwZjczMWUyMjk1,PT0=,RGF0YSBhbmQgQUk=%252FdfOthers%252FdfOTRiYmU4NTQtNWY4NC03Y2QyLWZjYWUtOGIxYmFmZjkyZThk,PT0=,RGVtbw==%252Flfbd96a596-00fe-47ef-8362-207f8a79446d//?mode=view) of the [watsonx Assistant L4 Hands-On Lab](https://yourlearning.ibm.com/activity/AB-181A9516DB5E).

See [this video](https://ibm.seismic.com/app#/doccenter/861ea1fd-99e0-44d7-9135-85412e5c28d1/doc/%252Fdd3359e5f7-a856-a91b-7688-41024b2ac637%252FdfNTY4NmVhOWItY2RkNS04ZWY3LTZkNzItZTQwZjczMWUyMjk1,PT0=,RGF0YSBhbmQgQUk=%252FdfOthers%252FdfOTRiYmU4NTQtNWY4NC03Y2QyLWZjYWUtOGIxYmFmZjkyZThk,PT0=,RGVtbw==%252Flf377af44e-802a-4d27-b523-c69992c1e502//?mode=view) for more details on the lab content.

**Comment by maurelya** [comment]
Option 2 of this lab uses the beta version of Conversational Search using IBM Granite. This option requires submitting a [request](https://form.asana.com/?k=U0gIIpwhM2_LY8r8LC_qDw&d=8612789739828) for the beta version which has a 2-day turnaround time. Participants will have to submit requests for the beta version at least 2 days before the workshop or they can do option 2 on their own time.
